org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
#org.gradle.daemon=true
#org.gradle.parallel=true
#org.gradle.java.installations.auto-download=false

## Environment Properties
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.20
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

## Mod Properties
mod_id=fermiumbooter
mod_name=FermiumBooter
mod_license=LGPL3
mod_version=1.0.0
mod_authors=Nischhelm
mod_description=Library to conditionally apply Mixins
mod_credits=fonnymunkey for 1.12.2 fermiumbooter
mod_side=BOTH